### ISSUE TITLE
Support Custom Classpath and Command Line Settings for starting BBj Programs

### ISSUE THREAD

**Issue by StephanWald** [BBx-Kitchen/bbj-language-server#231]

**Comment by bbrennanbasis** [comment]
Part of this issue has been resolved. There's now a "bbj.classpath" field in settings.json that uses the provide classpath name for starting applications.

**Comment by StephanWald** [comment]
## Status & scope for a clean reimplementation

### Already on `main` (partial)
`Commands.cjs` `run` currently builds:
```
"${bbj}" -q -CP<bbj.classpath> -c"<bbj.configPath>" -WD"<fileDir>" "<file>"
```
So **classpath** (`bbj.classpath`), **config file** (`bbj.configPath`), and **working directory** (auto = file's dir) are already configurable.

### The gap (what this issue still needs)
The rest of the BBj launch command line is **not** exposed for running programs — thin-client host/port, SSL, session monitoring, user/terminal, look-and-feel, debug, MDI, etc. That's the "Command Line Settings" half of this issue.

### Reference (ingested)
Authoritative option list: [Running from the command line — BASIS documentation](https://documentation.basis.cloud/BASISHelp/WebHelp/usr/BBj_Components/BBjServices/Thin_Client/running_from_the_command_line.htm)

General syntax: `bbj {options} {<program> {- <arglist>}}`

| Flag | Meaning |
|------|---------|
| `-a<string>` | Associate SysConsole settings with an application name |
| `-c<file>` | Configuration file on remote machine *(main: `bbj.configPath`)* |
| `-d` | Debug mode (debug in BBj WinConsole) |
| `-n<string>` | Associate SysConsole settings with a name (pairs with `-a`) |
| `-q` | Suppress start-up message and splash window *(main: always on)* |
| `-t<alias>` | Terminal alias from config; returned by `FID(0)` |
| `-u<user id>` | User account for Data Server / AppServer access |
| `-CP<name>` | Session-specific classpath (SSCP); `!!` JAR prefix in BBj 25.00+ *(main: `bbj.classpath`)* |
| `-FC` | Fat Client mode (obsolete since BBj 5.00) |
| `-LF<laf>` | Look and feel (default, cross, none, vpro5, FlatLaf options) |
| `-LO` | Load but do not run the program |
| `-LP<port>` | Port Request Server port (default 2008) |
| `-MDI<mode>` | MDI mode (BBj 9.0+) |
| `-RH<host>` | Remote ThinClientServer/STCS host or IP |
| `-RP<port>` | TCS port on remote machine (default 2003; STCS 2103) |
| `-SI<file>` | Custom splash image (BBj 25.03+, client-available) |
| `-SC` | Secure connection (TCPS ↔ STCS) |
| `-SMN<secs>` | Min splash display time (default 2; BBj 19.22+) |
| `-SMX<secs>` | Max splash display time (default 300; BBj 19.22+) |
| `--keystore=<path>` | Keystore for SSL/TLS with `-SC` |
| `--keypass=<pw>` | Keystore password |
| `--message="<msg>"` | Fallback for `BBjSessionInfo::getMessage` (BBj 23+) |
| `-TC` | Thin Client mode |
| `-WD<dir>` | Server working directory *(main: auto = file's dir)* |
| `-TCPSpreload` | Check/start ThinClientProxyServer without starting interpreter (BBj 17.00+) |
| `-TCPSto<secs>` | TCPS death-wait timeout (BBj 17.00+) |
| `-TCPShb<secs>` | TCPS ProxyManagerServer heartbeat timeout (BBj 17.00+) |

### Implementation notes (lessons from PR #277, now closed)
PR #277 prototyped this as a `bbj.commandLineOptions` object + a `buildExecCommand()` assembler. Good raw material, but it predates the `Commands.cjs` rewrite and can't be rebased. When reimplementing on current `main`:

- **Do not relocate `bbj.classpath`.** #277 moved it to `bbj.commandLineOptions.classpath` — a breaking change; `bbj.classpath` is used by both `run` and `runWeb`. Keep it; **append** extra options rather than replacing `-CP`/`-WD`.
- **Keep the `-WD` default** (file's directory) when no working directory is set — #277 dropped it.
- **Keep `-q` behavior** as-is unless deliberately overridden.
- **Decide scope:** GUI `run` only, or `run` + `runBUI` + `runDWC` too.
- Use the full flag catalogue above (richer than #277's) with per-flag descriptions from the BASIS doc.

**Comment by StephanWald** [comment]
**Triage → enhancement** (partially implemented). `bbj.classpath`, `bbj.configPath`, and the working directory (`-WD`) are already wired into the `run` command. Remaining work: expose the broader thin-client CLI flags (host/port, SSL, LAF, MDI, debug, …) via a new setting, **appended** to the launch command. @StephanWald's 2026-07-16 comment has the authoritative flag list + constraints. Labeled `enhancement`, `BBj integration and infrastructure`.
